name: SunsetHub
version: '1.0-SNAPSHOT'
main: dev.binarycodee.sunsethub.Core
depends: [NBTAPI, LuckPerms, PlaceholderAPI]
commands:
  sunsethub:
  spawn:
  setspawn:
  parkour:
  gmc:
  gms:
  gmsp:
  gma:
  fly:
  tp:
  tpall:
  tphere: